- name: install subsonic package
  apt:
    deb: "https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-{{ subsonic_version }}.deb"
    allow_unauthenticated: yes
    state: present

- name: stop subsonic
  service:
    name: subsonic
    state: stopped
    enabled: yes

- name: /var/subsonic permissions
  file:
    path: /var/subsonic
    owner: subsonic
    group: subsonic
    recurse: yes

- name: /usr/share/subsonic permissions
  file:
    path: /usr/share/subsonic
    owner: subsonic
    group: subsonic
    recurse: yes

- lineinfile:
    line: "SUBSONIC_USER='subsonic'"
    dest: "/etc/default/subsonic"
    regexp: '^SUBSONIC_USER'
  notify:
    - restart subsonic

- lineinfile:
    line: "SUBSONIC_ARGS='--max-memory=250 --default-music-folder=/s3fs/subsonic/music'"
    dest: "/etc/default/subsonic"
    regexp: '^SUBSONIC_ARGS'
  notify:
    - restart subsonic

- lineinfile:
    line: "LicenseCode={{ subsonic_license_key }}"
    dest: '/var/subsonic/subsonic.properties'
    regexp: '^LicenseCode'
    insertafter: EOF
    create: yes

- lineinfile:
    line: "LicenseEmail={{ subsonic_license_email }}"
    dest: '/var/subsonic/subsonic.properties'
    regexp: '^LicenseEmail'
    insertafter: EOF
    create: yes
  notify:
    - restart subsonic
