- name: create subsonic group
  group:
    name: subsonic
    system: yes
  register: subsonic_group

- name: create subsonic user
  user:
    name: subsonic
    comment: "Subsonic user"
    group: subsonic
    system: yes
    state: present
  register: subsonic_user

- name: install s3fs package
  apt:
    name: s3fs
  register: s3fs_package

- name: create subsonic directory
  file:
    path: /s3fs/subsonic
    state: directory
    owner: root
    group: root
  when: s3fs_package|changed

- name: create s3 mountpoint
  mount:
    path: /s3fs/subsonic
    src: "{{ s3fs_bucket_name }}:/"
    fstype: fuse.s3fs
    opts: "_netdev,iam_role={{ s3fs_iam_role }},endpoint={{ s3fs_aws_region }},allow_other,mp_umask=0022,uid={{ subsonic_user.uid }},gid={{ subsonic_group.gid }}"
    state: mounted
