- name: create madsonic group
  group:
    name: madsonic
    system: yes
  register: madsonic_group

- name: create madsonic user
  user:
    name: madsonic
    comment: "Madsonic user"
    group: madsonic
    system: yes
    state: present
  register: madsonic_user

- name: install s3fs package
  apt:
    name: s3fs
  register: s3fs_package

- name: create madsonic directory
  file:
    path: /s3fs/madsonic
    state: directory
    owner: root
    group: root
  when: s3fs_package|changed

- name: create s3 mountpoint
  mount:
    path: /s3fs/madsonic
    src: "{{ s3fs_bucket_name }}:/"
    fstype: fuse.s3fs
    opts: "_netdev,iam_role={{ s3fs_iam_role }},endpoint={{ s3fs_aws_region }},allow_other,mp_umask=0022,uid={{ madsonic_user.uid }},gid={{ madsonic_group.gid }}"
    state: mounted
