- name: create subsonic group
  group:
    name: subsonic
    system: yes

- name: create subsonic user
  user:
    name: subsonic
    comment: "Subsonic user"
    group: subsonic
    system: yes
    state: present
  register: subsonic_user

- name: install s3fs package
  apt:
    name: s3fs

- name: create subsonic directory
  file:
    path: /s3fs/subsonic
    state: directory
    owner: root
    group: root

- name: create s3 mountpoint
  mount:
    path: /s3fs/subsonic
    src: "{{ s3fs_bucket_name }}:/"
    fstype: fuse.s3fs
    opts: "_netdev,storage_class=standard_ia,iam_role={{ s3fs_iam_role }},endpoint={{ s3fs_aws_region }},user_id={{ subsonic_user.uid }},use_cache=/tmp/s3cache"
    state: mounted
