- hosts: default
  connection: local
  vars:
    subsonic_version:  "{{ lookup('env', 'SUBSONIC_VERSION') }}"
    subsonic_license_key: "{{ lookup('env', 'SUBSONIC_LICENSE_KEY') }}"
    s3fs_bucket_name: "{{ lookup('env', 'S3FS_BUCKET_NAME') }}"
    s3fs_aws_region: "{{ lookup('env', 'S3FS_AWS_REGION') }}"
    s3fs_iam_role: "{{ lookup('env', 'S3FS_IAM_ROLE') }}"
  roles:
    - java
    - s3fs
    - subsonic
