- hosts: default
  connection: local
  vars:
    madsonic_license_key: "{{ lookup('env', 'MADSONIC_LICENSE_KEY') }}"
    madsonic_license_email: "{{ lookup('env', 'MADSONIC_LICENSE_EMAIL') }}"
    madsonic_redirect_from: "{{ lookup('env', 'MADSONIC_REDIRECT_FROM') }}"
    s3fs_bucket_name: "{{ lookup('env', 'S3FS_BUCKET_NAME') }}"
    s3fs_aws_region: "{{ lookup('env', 'S3FS_AWS_REGION') }}"
    s3fs_iam_role: "{{ lookup('env', 'S3FS_IAM_ROLE') }}"
  roles:
    - java
    - s3fs
    - madsonic
