madsonic_license_key: "{{ lookup('env', 'MADSONIC_LICENSE_KEY') }}"
madsonic_license_email: "{{ lookup('env', 'MADSONIC_LICENSE_EMAIL') }}"
madsonic_redirect_from: "{{ lookup('env', 'MADSONIC_REDIRECT_FROM') }}"
